### ISSUE TITLE
这个是python几跑的

### ISSUE THREAD

**Issue by wbteve** [airzhangfish/blockchaincat#1]
M_0_3_centos core]# python3.6 ./bcserver.py 5000
Traceback (most recent call last):
  File "./bcserver.py", line 4, in <module>
    from flask import Flask, jsonify, request
ImportError: cannot import name 'Flask'

**Comment by wbteve** [comment]
python3.4 blockchaincat/core/bcserver.py 5000
  File "blockchaincat/core/bcserver.py", line 64
    response = requests.post(f'http://{node}/trans_sync',data=valuesstr)
                                                       ^
SyntaxError: invalid syntax

**Comment by airzhangfish** [comment]
use python3.6
